### ISSUE TITLE
Chapter 2 AudioLooper_Starter

### ISSUE THREAD

**Issue by sunyazhou13** [tapharmonic/Learning-AV-Foundation#12]
when I use 
`[nsnc addObserver:self
                 selector:@selector(handleInterruption:)
                     name:AVAudioSessionInterruptionNotification
                   object:[AVAudioSession sharedInstance]];
`

`else {
        //AVAudioSessionInterruptionTypeEnd
        AVAudioSessionInterruptionOptions options = [info[AVAudioSessionInterruptionOptionKey] unsignedIntegerValue];
        if (options == AVAudioSessionInterruptionOptionShouldResume) {
            [self play];
            if (self.delegate) {
                [self.delegate playbackBegan];
            }
        }`

music not playback to play   tell me  why    sunyazhou13@163.com

**Comment by bobmccune** [comment]
Your code looks correct. If playback is not resuming when the interruption ends, I'm guessing "options" is not equal to AVAudioSessionInterruptionOptionShouldResume.

**Comment by sunyazhou13** [comment]
options always is AVAudioSessionInterruptionOptionShouldResume

**Comment by sunyazhou13** [comment]
something wrong happen in playTime

**Comment by sunyazhou13** [comment]
you can have a try to run 

``` objc
- (void)handleInterruption:(NSNotification *)notification {
    NSDictionary *info  = notification.userInfo;
    AVAudioSessionInterruptionType type = [info[AVAudioSessionInterruptionTypeKey] unsignedIntegerValue];
    
    if (type == AVAudioSessionInterruptionTypeBegan) {
        //AVAudioSessionInterruptionTypeBegan
        [self stop];
        if ([self.delegate respondsToSelector:@selector(playbackStopped)]) {
            [self.delegate playbackStopped];
        }
    } else {
        //AVAudioSessionInterruptionTypeEnd
        AVAudioSessionInterruptionOptions options = [info[AVAudioSessionInterruptionOptionKey] unsignedIntegerValue];
        if (options == AVAudioSessionInterruptionOptionShouldResume) {
            [self play];
            if (self.delegate) {
                [self.delegate playbackBegan];
            }
        }
        NSLog(@"%lu",(unsigned long)options);
        
    }
}
```

**Comment by bobmccune** [comment]
It appears Apple must have changed some behavior (at least in iOS 10.3 beta, which is what I'm running). Previously, calling play on an AVAudioPlayer would always reactivate the audio session. That doesn't appear to be the case. The fix is it manually reactivate your audio session before calling play (e.g. [[AVAudioSession sharedInstance] setActive:YES error:nil];).

**Comment by sunyazhou13** [comment]
Oh  cool

I used this code ` [[AVAudioSession sharedInstance] setActive:YES error:&error];` it works 

``` objc
/**
 音频被打断 通知事件

 @param notification 音频信息
 */
- (void)handleInterruption:(NSNotification *)notification {
    NSDictionary *info  = notification.userInfo;
    AVAudioSessionInterruptionType type = [info[AVAudioSessionInterruptionTypeKey] unsignedIntegerValue];
    
    if (type == AVAudioSessionInterruptionTypeBegan) {
        //AVAudioSessionInterruptionTypeBegan
        [self stop];
        if ([self.delegate respondsToSelector:@selector(playbackStopped)]) {
            [self.delegate playbackStopped];
        }
    } else {
        //AVAudioSessionInterruptionTypeEnd
        AVAudioSessionInterruptionOptions options = [info[AVAudioSessionInterruptionOptionKey] unsignedIntegerValue];
        if (options == AVAudioSessionInterruptionOptionShouldResume) {
            NSError *error = nil;
            [[AVAudioSession sharedInstance] setActive:YES error:&error];
            [self play];
            if (self.delegate) {
                [self.delegate playbackBegan];
            }
            if (error) { NSLog(@"Active error:%@",error); }
        }
        NSLog(@"%lu",(unsigned long)options);
        
    }
}
```

Very  thanks , your book wrote very good and I've ever read like this
